### PR TITLE
Ignore PLT references from GCC intrinsic functions

### PR DESCRIPTION
**Pull request by pmur**
When LTO is enabled, intrinsic function usage no longer
bypasses the PLT.  They aren't really C functions and
don't really exist to rename above the ASM level which is
ignored by LTO.

Instead, just ignore such references and generate noise on
stderr if they are found.  There isn't much we can do, and
the performance impact is likely marginal.

This fixes Issue #150 for some definitions of fix.

### CODE REVIEW

**Comment by tuliom** [comment]
I wonder if this is a linker issue instead.
Interestingly, wcstod32 does get it right, but extendtftd does not.

The relocations do point to the expected symbol:
```
$ objdump -x ../libdfp-build/extendtftd.os
...
RELOCATION RECORDS FOR [.text]:
OFFSET           TYPE              VALUE
...
00000000000000fc R_PPC64_REL24     __GI___dpd_extenddftd
0000000000000110 R_PPC64_REL24     __GI___dpd_extenddftd
```

But it seems that, for this particular case, the linker prefers to use `__dpd_extenddftd` instead of `__GI___dpd_extenddftd`.

**Comment by pmur** [comment]
@tuliom did you mean __dpd_extend**tf**td above? __dpd_extendtftd implicitly calls the DF -> TD on both doubles in the ibm128 value, and combines them.  That is one of the few places you will see internal PLT references on ppc64/hard-dfp where the compiler cannot inline them.

**Comment by tuliom** [comment]
> did you mean __dpd_extendtftd above?

@pmur No.

>  __dpd_extendtftd implicitly calls the DF -> TD on both doubles in the ibm128 value, and combines them.

I agree with you that a call is needed. It should have been a local call, but the linker is replacing the local symbol with a call through the PLT.
I still do not understand why this is not linker bug.
I do understand asm statements are lost. I do not understand why it's correct to replace a local symbol with a global one.

**Review by tuliom — APPROVED** [review]
I now understand the output from objdump was actually coming from a fat LTO object and is not useful for the analysis here.

I still believe we have to find another solution to this, but there are no reasons to continue blocking this patch.
I need to study and I need more time for that.

With that said, I'm approving this patch and merging it.

Thanks for your patience!

**Pull request merged**
