### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by pmur**
* Fix the quantize test case inputs
* Fix the precision of the ulps test printfs

### CODE REVIEW

**Comment by pmur** [comment]
This resolves #14

**Comment by pmur** [comment]
This also partially fixes #16 for the _Decimal128 test.

**Comment by tuliom** [comment]
With the expception of the commit mentioned in my previous comment, all the rest LGTM.

**Comment by pmur** [comment]
Committed after fixing -1.0 -> -0.1.

**Pull request closed without merging**
