### PR TITLE
Get s390 working again

### PR DESCRIPTION
**Pull request by pmur**
make, and make check should work against the soft-dfp and z10 targets.

There is quite a bit of room for optimization on z. Based on what I saw, all the functions in convert_helpers.h should be fairly trivial to implement.

### CODE REVIEW

**Comment by pmur** [comment]
This should fix #43, and many other things I fixed along the way.

**Comment by pmur** [comment]
@tuliom No good deed goes unpunished. This is the "minimal" amount of work to get the s390 targets working again.

**Comment by tuliom** [comment]
Did you test if make-release.sh works after these changes?

**Comment by pmur** [comment]
It worked on PPC64LE. Though, for libdfp it isn't much more than running configure/make/make check.

**Comment by tuliom** [comment]
LGTM.

**Comment by pmur** [comment]
After reviewing, comparing, contrasting, and testing, I've merged patches 5 6 8 and 9. The others are duplicated by Stefan, and he took a few extra steps for the soft-fp and 31 bit variants too. Thus why I've merged most of his, as they are very similar if not the same as most of these.

**Pull request closed without merging**
